import { Team, TeamName } from "@/types";

export const TEAMS: Record<TeamName, Team> = {
  "Bengal Warriors": {
    name: "Bengal Warriors",
    players: [
      { name: "Maninder Singh", role: "Raider", no: 1 },
      { name: "Mohammad Nabibakhsh", role: "All-Rounder", no: 2 },
      { name: "Rinku Narwal", role: "Defender", no: 3 },
      { name: "Baldev Singh", role: "Defender", no: 4 },
      { name: "K. Prapanjan", role: "Raider", no: 5 },
      { name: "Sukesh Hegde", role: "Raider", no: 6 },
      { name: "Amit", role: "Defender", no: 7 },
    ],
    subs: [
      { name: "Jeeva Kumar", role: "Defender", no: 8 },
      { name: "Amit Nirwal", role: "Defender", no: 9 },
      { name: "Dharmendra Singh", role: "Defender", no: 10 },
      { name: "Ravindra Ramesh Kumawat", role: "Raider", no: 11 },
    ],
  },
  "Dabang Delhi": {
    name: "Dabang Delhi",
    players: [
      { name: "Naveen Kumar", role: "Raider", no: 12 },
      { name: "Joginder Narwal", role: "Defender", no: 13 },
      { name: "Chandran Ranjit", role: "Raider", no: 14 },
      { name: "Vishal Mane", role: "Defender", no: 15 },
      { name: "Meraj Sheykh", role: "All-Rounder", no: 16 },
      { name: "Anil Kumar", role: "Defender", no: 17 },
      { name: "Saeid Ghaffari", role: "Defender", no: 18 },
    ],
    subs: [
      { name: "Sumit Kumar", role: "Raider", no: 19 },
      { name: "Vijay", role: "All-Rounder", no: 20 },
      { name: "Neeraj Narwal", role: "Raider", no: 21 },
      { name: "Sombir", role: "Defender", no: 22 },
    ],
  },
  "U Mumba": {
    name: "U Mumba",
    players: [
      { name: "Fazel Atrachali", role: "Defender", no: 23 },
      { name: "Abhishek Singh", role: "Raider", no: 24 },
      { name: "Sandeep Narwal", role: "All-Rounder", no: 25 },
      { name: "Arjun Deshwal", role: "Raider", no: 26 },
      { name: "Surinder Singh", role: "Defender", no: 27 },
      { name: "Harendra Kumar", role: "Defender", no: 28 },
      { name: "Rohit Baliyan", role: "Raider", no: 29 },
    ],
    subs: [
      { name: "Ajinkya Kapre", role: "All-Rounder", no: 30 },
      { name: "Young Chang Ko", role: "Defender", no: 31 },
      { name: "Athul MS", role: "Raider", no: 32 },
      { name: "Dong Geon Lee", role: "Raider", no: 33 },
    ],
  },
  "Patna Pirates": {
    name: "Patna Pirates",
    players: [
      { name: "Pardeep Narwal", role: "Raider", no: 34 },
      { name: "Jaideep", role: "Defender", no: 35 },
      { name: "Neeraj Kumar", role: "Defender", no: 36 },
      { name: "Hadi Oshtorak", role: "All-Rounder", no: 37 },
      { name: "Jang Kun Lee", role: "Raider", no: 38 },
      { name: "Vikas Jaglan", role: "All-Rounder", no: 39 },
      { name: "Mohammad Esmaeil Maghsoudlou", role: "Raider", no: 40 },
    ],
    subs: [
      { name: "Monu", role: "Raider", no: 41 },
      { name: "Ravinder", role: "Defender", no: 42 },
      { name: "Ashish", role: "Defender", no: 43 },
      { name: "Surender Nada", role: "Defender", no: 44 },
    ],
  },
  "Telugu Titans": {
    name: "Telugu Titans",
    players: [
      { name: "Siddharth Desai", role: "Raider", no: 45 },
      { name: "Abozar Mighani", role: "Defender", no: 46 },
      { name: "Vishal Bhardwaj", role: "Defender", no: 47 },
      { name: "Rakesh Gowda", role: "Raider", no: 48 },
      { name: "Farhad Milaghardan", role: "All-Rounder", no: 49 },
      { name: "C. Arun", role: "Defender", no: 50 },
      { name: "Krishna", role: "Raider", no: 51 },
    ],
    subs: [
      { name: "Suraj Desai", role: "Raider", no: 52 },
      { name: "Krushna Madane", role: "Defender", no: 53 },
      { name: "Rajnish", role: "Raider", no: 54 },
      { name: "Ankit Beniwal", role: "Raider", no: 55 },
    ],
  },
  "Tamil Thaiwas": {
    name: "Tamil Thaiwas",
    players: [
      { name: "Ajay Thakur", role: "Raider", no: 56 },
      { name: "Manjeet Chhillar", role: "All-Rounder", no: 57 },
      { name: "Rahul Chaudhari", role: "Raider", no: 58 },
      { name: "Ran Singh", role: "All-Rounder", no: 59 },
      { name: "Mohan", role: "Defender", no: 60 },
      { name: "Himanshu", role: "Raider", no: 61 },
      { name: "M. Abhishek", role: "Raider", no: 62 },
    ],
    subs: [
      { name: "Milad Sheibak", role: "Defender", no: 63 },
      { name: "Vineet Sharma", role: "Defender", no: 64 },
      { name: "Anil Kumar", role: "Defender", no: 65 },
      { name: "Ajeet", role: "Defender", no: 66 },
    ],
  },
  "Gujarat Fortunegiants": {
    name: "Gujarat Fortunegiants",
    players: [
      { name: "Sunil Kumar", role: "Defender", no: 67 },
      { name: "Parvesh Bhainswal", role: "Defender", no: 68 },
      { name: "Rohit Gulia", role: "All-Rounder", no: 69 },
      { name: "Sachin Tanwar", role: "Raider", no: 70 },
      { name: "Sonu", role: "Raider", no: 71 },
      { name: "Gurvinder Singh", role: "Raider", no: 72 },
      { name: "Ankit", role: "Defender", no: 73 },
    ],
    subs: [
      { name: "Lalit Chaudhary", role: "Raider", no: 74 },
      { name: "Sumit", role: "Defender", no: 75 },
      { name: "Vinod Kumar", role: "All-Rounder", no: 76 },
      { name: "Ruturaj Koravi", role: "Defender", no: 77 },
    ],
  },
  "Haryana Steelers": {
    name: "Haryana Steelers",
    players: [
      { name: "Vikash Kandola", role: "Raider", no: 78 },
      { name: "Dharmaraj Cheralathan", role: "Defender", no: 79 },
      { name: "Prashanth Kumar Rai", role: "Raider", no: 80 },
      { name: "Vikas Kale", role: "Defender", no: 81 },
      { name: "Sunil", role: "Defender", no: 82 },
      { name: "Ravi Kumar", role: "Defender", no: 83 },
      { name: "Vinay", role: "Raider", no: 84 },
    ],
    subs: [
      { name: "Naveen", role: "Raider", no: 85 },
      { name: "Kuldeep Singh", role: "Defender", no: 86 },
      { name: "Amirhossein Mohammadmaleki", role: "Raider", no: 87 },
      { name: "Chand Singh", role: "Defender", no: 88 },
    ],
  },
  "Puneri Paltan": {
    name: "Puneri Paltan",
    players: [
      { name: "Nitin Tomar", role: "Raider", no: 89 },
      { name: "Surjeet Singh", role: "Defender", no: 90 },
      { name: "Girish Maruti Ernak", role: "Defender", no: 91 },
      { name: "Pawan Kumar Kadian", role: "Raider", no: 92 },
      { name: "Amit Kumar", role: "Raider", no: 93 },
      { name: "Shubham Shinde", role: "Defender", no: 94 },
      { name: "Manjeet", role: "All-Rounder", no: 95 },
    ],
    subs: [
      { name: "Emad Sedaghatnia", role: "Raider", no: 96 },
      { name: "Hadi Tajik", role: "Defender", no: 97 },
      { name: "Sagar Krishna", role: "Defender", no: 98 },
      { name: "Darshan Kadian", role: "Raider", no: 99 },
    ],
  },
  "Jaipur Pink Panthers": {
    name: "Jaipur Pink Panthers",
    players: [
      { name: "Deepak Niwas Hooda", role: "All-Rounder", no: 100 },
      { name: "Sandeep Dhull", role: "Defender", no: 101 },
      { name: "Amit Hooda", role: "Defender", no: 102 },
      { name: "Nilesh Salunke", role: "Raider", no: 103 },
      { name: "Deepak Narwal", role: "Raider", no: 104 },
      { name: "Vishal", role: "Defender", no: 105 },
      { name: "Sachin Narwal", role: "Raider", no: 106 },
    ],
    subs: [
      { name: "Ajinkya Pawar", role: "Raider", no: 107 },
      { name: "Pavan TR", role: "Defender", no: 108 },
      { name: "Lokesh Kaushik", role: "Defender", no: 109 },
      { name: "Dong Geon Lee", role: "Raider", no: 110 },
    ],
  },
  "UP Yoddha": {
    name: "UP Yoddha",
    players: [
      { name: "Shrikant Jadhav", role: "Raider", no: 111 },
      { name: "Nitesh Kumar", role: "Defender", no: 112 },
      { name: "Sumit", role: "Defender", no: 113 },
      { name: "Monu Goyat", role: "Raider", no: 114 },
      { name: "Rishank Devadiga", role: "Raider", no: 115 },
      { name: "Surender Gill", role: "Raider", no: 116 },
      { name: "Ashu Singh", role: "Defender", no: 117 },
    ],
    subs: [
      { name: "Gulveer Singh", role: "Raider", no: 118 },
      { name: "Amit", role: "Defender", no: 119 },
      { name: "Narender", role: "Raider", no: 120 },
      { name: "Mohsen Maghsoudlou", role: "All-Rounder", no: 121 },
    ],
  },
  "Bengaluru Bulls": {
    name: "Bengaluru Bulls",
    players: [
      { name: "Pawan Sehrawat", role: "Raider", no: 34 },
      { name: "Mahender Singh", role: "Defender", no: 35 },
      { name: "Amit Sheoran", role: "Defender", no: 36 },
      { name: "Rohit Kumar", role: "Raider", no: 37 },
      { name: "Saurabh Nandal", role: "Defender", no: 38 },
      { name: "Sumit Singh", role: "Raider", no: 39 },
      { name: "Ankit", role: "Defender", no: 40 },
    ],
    subs: [
      { name: "Banty", role: "Raider", no: 41 },
      { name: "Mohit Sehrawat", role: "Defender", no: 42 },
      { name: "Raju Lal Choudhary", role: "Defender", no: 43 },
      { name: "Vinod Kumar", role: "All-Rounder", no: 44 },
    ],
  },
};

export const POSITIONS = {
  Defender: ["Left Corner", "Right Corner", "Left Cover", "Right Cover"],
  Raider: ["Left In", "Right In"],
  "All-Rounder": ["Middle"],
};
